project:
  type: website
  output-dir: docs

website:
  title: "Prashanta Kumar Mitra"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: spacelab
    css: styles.css