---
title: "Publications"
format: html
---

# Publications

## Research Articles

1.  **Mitra P K, Karmakar R, Nandi R, Gupta S.** 2023. Low-cost rapid workflow for honey adulteration detection by UV--Vis spectroscopy in combination with factorial design, response surface methodology, and supervised machine learning classifiers. *Bioresource Technology Reports*. [doi.org/10.1016/j.biteb.2022.101327](https://doi.org/10.1016/j.biteb.2022.101327)

2.  **Mitra P K, Adhikary R, Mandal P, Kundu A, Mandal V.** 2022. Assessment of mycorrhizal association of a threatened medicinal plant Clerodendrum indicum (L.) O. Kuntze (Verbenaceae) in different ecological variations. *Brazilian Journal of Microbiology*. [doi.org/10.1007/s42770-022-00805-2](https://doi.org/10.1007/s42770-022-00805-2)

3.  **Singh L J, Dey B C, Mitra P K, Sharma G P, Kushwaha C P.** 2024. Diversity of reproductive phenology of trees in the tropical evergreen forest of Andaman and Nicobar Islands, India. *Tropical Ecology*. <https://doi.org/10.1007/s42965-024-00326-z>

4.  **Upadhyay A K, Gogoi R, Mitra P K.** 2021. Ethnobotany of the genus Elatostema J.R. Forster & G. Forster (Urticaceae). *Ethnobotany Research and Applications*. <https://doi.org/10.32859/era.27.01.1-24>

5.  **Mandal V, Ghosh N N, Mitra P K, Mandal S, Mandal V.** 2022. Production and characterization of a broad-spectrum antimicrobial 5-butyl-2-pyridine carboxylic acid from Aspergillus fumigatus nHF-01. *Scientific Reports (Nature Publishing Group)*. <https://doi.org/10.1038/s41598-022-09925-z>

6.  **Bandyopadhyay B, Das S, Mitra P K, Kundu A, Adhikary R, Mandal V, Mandal N C.** 2022. Characterization of two new strains of Lactococcus lactis for their probiotic efficacy over commercial synbiotics consortia. *Brazilian Journal of Microbiology*. <https://doi.org/10.1007/s42770-022-00685-6>

7.  **Parvin A, Adhikary R, Guha S, Mitra P K, Mandal V.** 2022. Antibiofilm and antimicrobial activity of biosurfactants from two Lactiplantibacillus pentosus strains against food and topical pathogens. *Journal of Food Processing and Preservation*. <https://doi.org/10.1111/jfpp.16927>

8.  **Bandyopadhyay B, Mitra P K, Mandal V, Mandal N C.** 2021. Novel fructooligosaccharides of Dioscorea alata L. tuber have prebiotic potentialities. *European Food Research and Technology*. <https://doi.org/10.1007/s00217-021-03872-1>

9.  **Adhikary R, Kundu S K, Maiti P K, Mitra P K, Mandal S, Mandal V.** 2020. Effect of different stimuli on twitching behavior of endophytic bacteria isolated from Loranthus sp. Jacq. *Antonie Van Leeuwenhoek*. <https://doi.org/10.1007/s10482-020-01458-7>

10. **Chanda C, Mitra P K, Fraser‐Jenkins C R, Rawat V K.** 2024. The genus Athyrium (Woodsiaceae) in Arunachal Pradesh state, India. *Phytotaxa*. <https://doi.org/10.11646/phytotaxa.636.4.1>

11. **Karmakar R, Mitra P K, Nandi R, Gupta S.** 2022. Habitat specificity of phytolith production in Acrostichum aureum L. *NDC E-BIOS*. <https://www.ndcebios.in/v2n1/2022020105.pdf>

12. **Das D, Mitra P K, Gupta S.** 2021. Evaluation of Cytotoxicity Induced by the Anti-Cancerous Drugs Doxorubicin and Erlotinib in Allium cepa Assay for Eco-Safety Monitoring. *Cytologia*. <https://doi.org/10.1508/cytologia.86.195>

13. **Gupta S D, Das D, Mitra P K, Halder S, Datta A.** 2020. Assessment of Cytotoxicity Induced by Hazardous Chemotherapeutic Drugs Cyclophosphamide and 5-Fluorouracil in Allium cepa Assay for Ecological Safety. *Cytologia*. <https://doi.org/10.1508/cytologia.85.151>

14. **Garai P K, Mitra P K, Sil S K.** 2018. Assessment on Phytoplankton Diversity from English Bazaar Block of Malda District. *Journal of Agroecology and Natural Resource Management*. <https://www.researchgate.net/profile/Prashanta-Mitra/publication/349521598_Assessment_on_Phytoplankton_Diversity_from_English_Bazaar_Block_of_Malda_District/links/6034dacf92851c4ed58e5a15/Assessment-on-Phytoplankton-Diversity-from-English-Bazaar-Block-of-Malda-District.pdf>

## Book Chapters

1.  **Mitra P K, Adhikary R, Mandal V.** 2023. Current status of Mycorrhizal biofertilizer in crop improvement and its future prospects. In: Mathur, P., Kapoor, R., Roy, S. (Eds) Microbial Symbionts and Plant Health: Trends and Applications for Changing Climate. Rhizosphere Biology. <https://doi.org/10.1007/978-981-99-0030-5_17>

2.  **Mitra P K, Mandal V.** 2022. Post-Green Revolution Degradation of agricultural land in India: Role of mycorrhizae in the sustainability of agriculture and ecosystems. In: Roy, S., Mathur, P., Chakraborty, A.P., Saha, S.P. (Eds) Plant Stress: Challenges and Management in the New Decade. Advances in Science, Technology & Innovation. <https://doi.org/10.1007/978-3-030-95365-2_22>
